//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestApplication.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class MeterReading
    {
        public int Id { get; set; }
        public int AccountId { get; set; }
        public System.DateTime MeterReadDate { get; set; }
        public int MeterReadValue { get; set; }
    }
}
